CREATE TABLE IF NOT EXISTS `EQUIP_TYPE`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `CODE`        VARCHAR(50) NOT NULL UNIQUE COMMENT '타입코드',
    `NAME`        VARCHAR(50) NOT NULL UNIQUE COMMENT '타입명',
    `DESCRIPTION` VARCHAR(200) DEFAULT NULL COMMENT '설명',
    `ICON`        VARCHAR(100) DEFAULT NULL COMMENT '아이콘'
);
CREATE TABLE IF NOT EXISTS `EQUIP_GROUP`
(
    `ID`            BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `NAME`          VARCHAR(50)  NOT NULL UNIQUE COMMENT '그룹명',
    `DESCRIPTION`   VARCHAR(400) NOT NULL COMMENT '설명',
    `PARENT_ID`     BIGINT DEFAULT NULL COMMENT '부모그룹고유키',
    `DISPLAY_ORDER` INT    DEFAULT 0 COMMENT '같은깊이인경우정렬순서',
    CONSTRAINT FK_EQUIP_GROUP_EQUIP_GROUP FOREIGN KEY (`PARENT_ID`) REFERENCES EQUIP_GROUP (`ID`)
);
CREATE TABLE IF NOT EXISTS `EQUIP`
(
    `ID`              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `IP`              VARCHAR(15)  NOT NULL COMMENT '장비IP',
    `NAME`            VARCHAR(30)  NOT NULL UNIQUE COMMENT '장비명',
    `EQUIP_TYPE_CODE` VARCHAR(50)  NOT NULL COMMENT '장비타입',
    `OS`              VARCHAR(100) NOT NULL COMMENT '운영체제',
    `ENABLE`          BOOL        DEFAULT TRUE COMMENT '사용여부',
    `PARENT_ID`       BIGINT      DEFAULT NULL COMMENT '부모장비고유키',
    `EQUIP_GROUP_ID`  BIGINT      DEFAULT NULL COMMENT '장비그룹고유키',
    `DESCRIPTION`     VARCHAR(30) DEFAULT NULL COMMENT '설명',
    CONSTRAINT FK_EQUIP_EQUIP_TYPE FOREIGN KEY (`EQUIP_TYPE_CODE`) REFERENCES EQUIP_TYPE (`CODE`),
    CONSTRAINT FK_EQUIP_EQUIP FOREIGN KEY (`PARENT_ID`) REFERENCES EQUIP (`ID`),
    CONSTRAINT FK_EQUIP_EQUIP_GROUP FOREIGN KEY (`EQUIP_GROUP_ID`) REFERENCES EQUIP_GROUP (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
