server:
  port: 8003

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/devh?rewriteBatchedStatements=true
    username: devh
    password: 1234
  sql:
    init:
      platform: mariadb
      schema-locations: classpath*:db/schema-${spring.sql.init.platform}.sql
#      data-locations: classpath*:db/data-${spring.sql.init.platform}.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: false

#logging:
#  config: classpath:log4j2.xml
